# Generated by Django 4.2.2 on 2023-06-22 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=250)),
                ('total_reviews', models.IntegerField(blank=True, null=True)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('lot_long', models.CharField(max_length=50)),
                ('average_cost_for_2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('online_delivery', models.BooleanField(default=False)),
                ('table_booking', models.BooleanField(default=False)),
                ('delivering_now', models.BooleanField(default=False)),
                ('table_reservation_supported', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FoodDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('restaurant', models.ManyToManyField(to='search.restaurant')),
            ],
        ),
    ]
